{{- if and .Values.frontend.enabled .Values.externalSecrets.enabled -}}
{{- $ctx := merge (dict "workload" "frontend" "workloadKey" "frontend") . -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.frontend.envFromSecret.name }}
  labels:
    {{- include "sentinelrag.workload.labels" $ctx | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ .Values.frontend.envFromSecret.name }}
    creationPolicy: Owner
  data:
    {{- range .Values.frontend.envFromSecret.remoteKeys }}
    - secretKey: {{ . }}
      remoteRef:
        key: {{ printf "%s/frontend/%s" $.Release.Name . }}
    {{- end }}
{{- end -}}
