{{- if and .Values.frontend.enabled .Values.frontend.serviceAccount.create -}}
{{- $ctx := merge (dict "workload" "frontend" "workloadKey" "frontend") . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sentinelrag.workload.serviceAccountName" $ctx }}
  labels:
    {{- include "sentinelrag.workload.labels" $ctx | nindent 4 }}
  {{- with .Values.frontend.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end -}}
