{{- if and .Values.api.enabled .Values.api.ingress.enabled -}}
{{- $ctx := merge (dict "workload" "api" "workloadKey" "api") . -}}
{{- $svcName := include "sentinelrag.workload.fullname" $ctx -}}
{{- $svcPort := .Values.api.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $svcName }}
  labels:
    {{- include "sentinelrag.workload.labels" $ctx | nindent 4 }}
  {{- with .Values.api.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ include "sentinelrag.workload.ingressClass" $ctx }}
  {{- with .Values.api.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.api.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $svcName }}
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
{{- end -}}
