{{- if and .Values.api.enabled .Values.api.pdb.enabled -}}
{{- $ctx := merge (dict "workload" "api" "workloadKey" "api") . -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "sentinelrag.workload.fullname" $ctx }}
  labels:
    {{- include "sentinelrag.workload.labels" $ctx | nindent 4 }}
spec:
  minAvailable: {{ .Values.api.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "sentinelrag.workload.selectorLabels" $ctx | nindent 6 }}
{{- end -}}
